<h1 align="center"> Tushar JAIN </h1>
<h2 align="center"> FINA 4414 Homework 2 </h1>

<h3>Answer 1</h3> 
<p>(b)	R stores matrix elements as a vector in a column-major order, therefore the aMatrix will be treated as c(1, 3 , 2, 4). R also uses the concept of re-cycling, which means that if the number of elements in one vector is shorter than the other, R will cycle through the elements of the shorter vector from the beginning to make up for the short length. R does output a warning message however.</p>
<p>(a)<p>

In [1]:
aMatrix <- cbind(c(1, 3), c(2, 4))
aMatrix * c(2,4,1)

Warning message:
In aMatrix * c(2, 4, 1): longer object length is not a multiple of shorter object length

     [,1] [,2]
[1,]    2    2
[2,]   12    8

<h3>Answer 2</h3>
```
(a) myEmployee$name[1]
    myEmployee[[1]][1]
(b) myEmployee[1]$name[1]
    myEmployee[1][[1]][1]
```

<h3>Answer 3</h3>
<p>The argument searches for the regular expression “Software Engineer” in the data frame, all2006, and returns a data frame with “Software Engineer” appearing in at least one of the columns.</p>

<h3>Answer 4</h3>

```
(a) all2006[which(all2006$Prevailing_Wage_Job_Title == "Software Engineer"), ]
    1785 line items match this criterion
(b) all2006[grep("Software Engineer", all2006$Prevailing_Wage_Job_Title), ]
    7993 line items match this criterion
```

In [2]:
all2006 <- read.csv("2006.csv",header=TRUE,as.is=TRUE)
all2006$Wage_Offered_From <- as.numeric(gsub("\\$","", all2006$Wage_Offered_From))
all2006$Prevailing_Wage_Amount <- as.numeric(gsub("\\$","", all2006$Prevailing_Wage_Amount))
all2006$Wage_Offered_To <- as.numeric(gsub("\\$","", all2006$Wage_Offered_To))
all2006 <- all2006[all2006$Wage_Per == 'Year', ]
all2006 <- all2006[all2006$Wage_Offered_From > 20000, ]
all2006 <- all2006[all2006$Prevailing_Wage_Amount > 200, ]

se2006 <- all2006[which(all2006$Prevailing_Wage_Job_Title == "Software Engineer"), ]
cat("(a) ")
cat(dim(se2006)[1])
cat(" line items match this creiteria\n")

se2006 <- all2006[grep("Software Engineer", all2006$Prevailing_Wage_Job_Title), ]
cat("(b) ")
cat(dim(se2006)[1])
cat(" line items match this creiteria\n")

(a) 1785 line items match this creiteria
(b) 7993 line items match this creiteria

<h3>Answer 5</h3>

In [3]:
aList <- list(name = c("stock1", "stock2", "stock3", "stock4"), cap.usd = c(5,6,7,8))
myDf <- data.frame(aList, stringsAsFactors = FALSE)

# Answer
grepDf <- function (aPattern, aDataFrame) {    
    A <- function(x) {
        any(grepl(aPattern, x))
    }
    apply(aDataFrame, 1, A) # Applies to each element in all the rows
}

# Test Arguements
grepDf("stock3", myDf)
grepDf("stock1|stock3", myDf)
grepDf(8, myDf)
myDf[grepDf(8, myDf), ]

[1] FALSE FALSE  TRUE FALSE

[1]  TRUE FALSE  TRUE FALSE

[1] FALSE FALSE FALSE  TRUE

    name cap.usd
4 stock4       8

<h3>Answer 6</h3>

In [4]:
countries <- unique(all2006$Alien_Citizenship_Country)
uniqueCountries <- length(countries)
cat("(a)", uniqueCountries, " unique countries")

(a) 175  unique countries

In [5]:
# declare vectors of means and standard deviations for each country
means <- vector(mode = "numeric", length = uniqueCountries)
sds <- vector(mode = "numeric", length = uniqueCountries)

for(i in 1:uniqueCountries) {
    filter <- all2006[which(all2006$Alien_Citizenship_Country == countries[i]),] # filter the data frame for use
    means[i] <- round(mean(filter$Wage_Offered_From, na.rm = TRUE), digits=4) # add elements to the correct index
    sds[i] <- round(sd(filter$Wage_Offered_From, na.rm = TRUE), digits=2)
}

countryList <- list(country = countries, mean = means, sd = sds) # make a list and the dataframe
df = data.frame(countryList, stringsAsFactors=FALSE)
df <- df[with(df, order(-mean)), ] # sort the dataframe
df <- df[1:10, ] # chose the top 10 and print the dataframe
cat("(b)\n")
df

(b)

                         country      mean        sd
108           ST KITTS AND NEVIS 261194.67 339908.31
126                      BAHRAIN 156000.00 104651.80
49                         SYRIA 130478.96  70391.96
169                        QATAR 126300.00        NA
137                      ERITREA 113520.00  91384.98
99                        KUWAIT 105078.64  76367.50
128 DEMOCRATIC REPUBLIC OF CONGO 104000.00 106080.16
134                       NORWAY 101357.90  51998.38
77                      SLOVENIA  95599.25  38712.09
148                    SWAZILAND  95280.00  47388.91

In [6]:
func <- function(x) {
    which(all2006$Alien_Citizenship_Country == x)
}
result <- lapply(countries, func)
attributes(result)$names <- countries # assign the correct name attribute to the indexes
cat("(c)")
result[['HONG KONG']] # answer preview

(c)

  [1]    38   462  1396  1600  1683  1880  2065  2610  2704  2880  2885  3495
 [13]  4451  4475  4564  5408  5551  6500  6578  7009  8535  8648  8692  8720
 [25]  8838  8860  8978  9583  9771 10133 10168 10355 10621 10777 10851 10992
 [37] 11121 11827 11856 12118 12149 12582 12985 13280 13946 14268 14824 15000
 [49] 15057 15653 15674 15845 15973 16399 16407 16867 17186 17537 17828 18058
 [61] 18219 18284 18629 18807 19014 19322 19560 19668 20454 20458 20473 20899
 [73] 21477 21503 21644 21958 22257 22904 23093 23117 23455 24317 24405 24499
 [85] 24768 25065 25083 25618 26101 26789 26827 26973 27667 27955 27956 28257
 [97] 29265 29305 29338 30043 30972 31021 32425 32596 32896 33234 33344 33665
[109] 33728 33791 33792 34116 34428 34529 34993 35058 35059 35206 35374 36226
[121] 36437 36614 36782 36838 36881 37005 37253 37667 38778 39212 39316 39718
[133] 39769 39835 39841 40474 40958 40978 41387 41508 41576 41648 41742 41774
[145] 41776 41789 41929 42474 43082 43551 43572 43647 43671 43677 43827 43873
[157] 43903 43928 44072 44092 44138 44155 44634 44638 44691 44700 44710 44724
[169] 44727 44731 44733 44771 44778 44779 44794 44798 44810 44895 44913 44963
[181] 44994 45230 45573 45643 45815 45859 45901 46139 46282 46497 46591 46647
[193] 46695 46714 46747 46752 46850 46884 47070 47305 47409 47410 47430 47481
[205] 47681 47908 48155 48289 48290 48712 48885 48910 48935 48989 49270 49601
[217] 49877 50535 50574 50587 50592 50599 50911 51013 51075 51220 51387 51437
[229] 51635 51805 51841 52019 52265 52386 52397 52433 52499

<h3>Answer 7</h3>

In [7]:
Sys.setlocale(locale="C")
yahoo <- all2006[grep("YAHOO", all2006$Employer_Name), ] # Choose Yahoo as employer
count <- table(yahoo$Alien_Citizenship_Country) # get the frequencies and sort
count <- sort(count, decreasing = TRUE)
cat("(a)")
head(count, 5) # answer display

[1] "C/C/C/C/C/en_US.UTF-8"

(a)

         INDIA          CHINA         CANADA    SOUTH KOREA UNITED KINGDOM
           101             47             19              8              8

In [8]:
na <- sum(is.na(all2006))
cat("(b) ", na, " NA's")

(b)  45137  NA's

<h3>Answer 8</h3>

In [9]:
a <- function(df) {
    n <- dim(df)[1]
    for( i in 1:n ) {
        aString = paste("x", i, sep="")
        assign(aString, df[i, ], pos=.GlobalEnv)
    }
}

b <- function(df) {
    n <- dim(df)[1]
    x <- NULL
    for( i in 1:n ) {
        x[[i]] <- df[i, ]
    }
}